port 26379
dir /tmp
loglevel notice

sentinel monitor mymaster 192.168.1.99 6379 2
sentinel down-after-milliseconds mymaster 5000
sentinel failover-timeout mymaster 10000
sentinel parallel-syncs mymaster 1

# Disable auto-config file rewriting to avoid permission issues in containers
sentinel deny-scripts-reconfig yes

