version: '3.8'

name: jj

services:
  clickhouse-01:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-${CLICKHOUSE_NODE_LOWER}-01
    hostname: clickhouse.${CLICKHOUSE_NODE_LOWER}.01
    ports:
      - "${CLICKHOUSE_PORT_HTTP_01}:8123"
      - "${CLICKHOUSE_PORT_TCP_01}:9000"
    volumes:
      - ${CLICKHOUSE_CONFIG_DIR_01}/config.xml:/etc/clickhouse-server/config.xml
      - ${CLICKHOUSE_CONFIG_DIR_01}/users.xml:/etc/clickhouse-server/users.xml
      - ${CLICKHOUSE_VOLUME_PATH_01}:/var/lib/clickhouse
    env_file:
      - .env
    networks:
      - docker-network

  clickhouse-02:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-${CLICKHOUSE_NODE_LOWER}-02
    hostname: clickhouse.${CLICKHOUSE_NODE_LOWER}.02
    ports:
      - "${CLICKHOUSE_PORT_HTTP_02}:8123"
      - "${CLICKHOUSE_PORT_TCP_02}:9000"
    volumes:
      - ${CLICKHOUSE_CONFIG_DIR_02}/config.xml:/etc/clickhouse-server/config.xml
      - ${CLICKHOUSE_CONFIG_DIR_02}/users.xml:/etc/clickhouse-server/users.xml
      - ${CLICKHOUSE_VOLUME_PATH_02}:/var/lib/clickhouse
    env_file:
      - .env
    networks:
      - docker-network

  tabix:
    image: spoonest/clickhouse-tabix-web-client:stable
    container_name: tabix-${CLICKHOUSE_NODE_LOWER}
    ports:
      - "8022:80"
    environment:
      - CLICKHOUSE_HOST=clickhouse.${CLICKHOUSE_NODE_LOWER}.01
      - CLICKHOUSE_PORT=8123
    depends_on:
      - clickhouse-01
      - clickhouse-02
    networks:
      - docker-network

networks:
  docker-network:
    external: true
