name: jj

services:
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOO_CFG_EXTRA="server.1=zookeeper:2888:3888"
      - ZOO_MY_ID=1
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_logs:/var/log/zookeeper
    networks:
      - docker-network
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5

  clickhouse-01:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-${CLICKHOUSE_NODE_LOWER}-01
    hostname: ${CLICKHOUSE_HOSTNAME}-01.internal
    ports:
      - "${CLICKHOUSE_PORT_HTTP_01}:8123"
      - "${CLICKHOUSE_PORT_TCP_01}:9000"
    volumes:
      - ${CLICKHOUSE_CONFIG_DIR_01}/config.xml:/etc/clickhouse-server/config.xml
      - ${CLICKHOUSE_CONFIG_DIR_01}/users.xml:/etc/clickhouse-server/users.xml
      - ${CLICKHOUSE_CONFIG_DIR_01}/users.d:/etc/clickhouse-server/users.d
      - ${CLICKHOUSE_CONFIG_DIR_01}/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ${CLICKHOUSE_VOLUME_PATH_01}:/var/lib/clickhouse
    env_file:
      - .env
    networks:
      - docker-network

  clickhouse-02:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-${CLICKHOUSE_NODE_LOWER}-02
    hostname: ${CLICKHOUSE_HOSTNAME}-02.internal
    ports:
      - "${CLICKHOUSE_PORT_HTTP_02}:8123"
      - "${CLICKHOUSE_PORT_TCP_02}:9000"
    volumes:
      - ${CLICKHOUSE_CONFIG_DIR_02}/config.xml:/etc/clickhouse-server/config.xml
      - ${CLICKHOUSE_CONFIG_DIR_02}/users.xml:/etc/clickhouse-server/users.xml
      - ${CLICKHOUSE_CONFIG_DIR_02}/users.d:/etc/clickhouse-server/users.d
      - ${CLICKHOUSE_CONFIG_DIR_02}/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ${CLICKHOUSE_VOLUME_PATH_02}:/var/lib/clickhouse
    env_file:
      - .env
    networks:
      - docker-network

networks:
  docker-network:
    external: true
