receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  debug/metrics:
    verbosity: basic
  clickhouse:
    endpoint: tcp://clickhouse:9000?dial_timeout=10s
    database: otel
    username: default
    compress: lz4
    async_insert: true
    create_schema: true
    ttl: 72h
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug ]
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug/metrics, clickhouse ]
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug, clickhouse ]